server:
  port: 8380
spring:
  profiles:
    active: dev
  application:
    name: judge
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost:3306}/cloud_oj?allowMultiQueries=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  rabbitmq:
    host: ${RABBIT_URL:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${SERVICE_HOST:${spring.cloud.client.ip-address}}:${SERVICE_PORT:${server.port}}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/
mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml